import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { FloatingWhatsApp, ScrollBasedLeadCapture } from "@/components/LazyComponents";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spacio Workspace | Best Premium Coworking Space in Bangalore | Basavanagudi & Jayanagar | Private Cabins, Dedicated Desks, Meeting Rooms, Virtual Office | 1Gbps WiFi | 24/7 Access | Near Bull Temple | Near Lalbagh | South Bangalore | Book Free Tour",
  description: "Bangalore's #1 premium coworking space for Gen Z entrepreneurs, startups, and freelancers in Basavanagudi. Private cabins (solo, 3-seater, 6-seater), dedicated desks, meeting rooms, and virtual offices. Lightning-fast 1Gbps WiFi, 24/7 secure access, modern amenities, vibrant community of 500+ members. Vastu-compliant workspace near Bull Temple and Lalbagh Botanical Gardens in South Bangalore. Affordable coworking space, flexible workspace solutions, startup office space, shared office, day pass coworking. Book your free tour today!",
  keywords: [
    "best coworking space in Bangalore",
    "coworking space Basavanagudi",
    "coworking space Jayanagar",
    "private office Bangalore",
    "dedicated desk Bangalore",
    "meeting room Bangalore",
    "virtual office Bangalore",
    "startup office Bangalore",
    "shared office Bangalore",
    "day pass coworking Bangalore",
    "rent office Bangalore",
    "coworking south bangalore",
    "basavanagudi coworking",
    "jayanagar coworking",
    "google ads coworking bangalore",
    "meta ads coworking bangalore",
    "facebook ads coworking bangalore",
    "llm friendly workspace",
    "ai startup workspace bangalore",
    "gen z coworking bangalore",
    "shared office space Bangalore",
    "flexible workspace Bangalore",
    "coworking space near me Bangalore",
    "best shared office Bangalore",
    "modern coworking Bangalore",
    "startup coworking space Bangalore",
    "freelancer workspace Bangalore",
    "entrepreneur office space Bangalore",
    "tech startup office Bangalore",
    "Gen Z coworking Bangalore",
    "affordable coworking Bangalore",
    "24/7 coworking space Bangalore",
    "private cabin Bangalore",
    "solo cabin coworking Bangalore",
    "team workspace Bangalore",
    "business address Bangalore",
    "professional workspace Bangalore",
    "productivity space Bangalore",
    "collaborative workspace Bangalore",
    "coworking space South Bangalore",
    "office space Basavanagudi",
    "office space Jayanagar",
    "tech coworking space Bangalore",
    "IT workspace Bangalore",
    "software company office space Bangalore",
    "developer workspace Bangalore",
    "programmer coworking Bangalore",
    "tech startup office Basavanagudi",
    "IT hub Bangalore",
    "techies workspace Bangalore",
    "coding space Bangalore",
    "Basavanagudi coworking",
    "Basavanagudi office space",
    "near Bull Temple",
    "near Lalbagh",
    "South Bangalore workspace",
    "premium tech workspace",
    "modern IT office",
    "startup hub Basavanagudi",
    "day pass coworking Bangalore",
    "day pass Basavanagudi",
    "day pass workspace",
    "virtual office Bangalore",
    "virtual office Basavanagudi",
    "virtual office services",
    "business address Bangalore",
    "private cabins Bangalore",
    "private cabins Basavanagudi",
    "2 seater cabin",
    "3 seater cabin",
    "6 seater cabin",
    "private office cabin",
    "office space Basavanagudi",
    "office space for rent",
    "rent office space Bangalore",
    "meeting rooms Bangalore",
    "meeting rooms Basavanagudi",
    "conference room rental",
    "book meeting room",
    "event space Basavanagudi",
    "coworking space near Bull Temple",
    "coworking space near Lalbagh",
    "Basavanagudi workspace",
    "South Bangalore coworking",
    "affordable office space Bangalore",
    "best coworking space South Bangalore",
    "coworking space Basavanagudi Bangalore",
    "office space near Bull Temple",
    "workspace near Lalbagh",
    "Basavanagudi business center",
    "Jayanagar business center",
    "flexible office space Bangalore",
    "monthly office rent Bangalore",
    "coworking membership Bangalore",
    "startup incubator Bangalore",
    "entrepreneur hub Bangalore",
    "freelancer hub Bangalore",
    "remote work space Bangalore",
    "work from home alternative Bangalore",
    "professional workspace Basavanagudi",
    "modern office space Basavanagudi",
    "tech workspace Bangalore",
    "IT office space Bangalore",
    "software development workspace",
    "digital nomad workspace Bangalore",
    "coworking community Bangalore",
    "business networking space Bangalore",
    "collaborative workspace Basavanagudi",
    "productivity space Basavanagudi",
    "creative workspace Bangalore",
    "innovation hub Bangalore",
    "startup workspace Basavanagudi",
    "small business office Bangalore",
    "team workspace Bangalore",
    "private workspace Bangalore",
    "quiet workspace Bangalore",
    "focused workspace Bangalore",
    "Vastu compliant office Bangalore",
    "Vastu compliant workspace",
    "zen workspace Bangalore",
    "peaceful workspace Bangalore",
    "serene workspace Bangalore",
    "calm workspace Bangalore",
    "productive workspace Bangalore",
    "inspiring workspace Bangalore",
    "motivational workspace Bangalore",
    "success workspace Bangalore",
    "growth workspace Bangalore",
    "premium workspace experience Bangalore",
    "luxury coworking Bangalore",
    "elite coworking space Bangalore",
    "exclusive workspace Bangalore",
    "boutique coworking Bangalore",
    "designer workspace Bangalore",
    "award winning coworking Bangalore",
    "top rated coworking Bangalore",
    "best rated coworking Bangalore",
    "5 star coworking Bangalore",
    "highly rated coworking Bangalore",
    "recommended coworking Bangalore",
    "trusted coworking Bangalore",
    "reliable coworking Bangalore",
    "established coworking Bangalore",
    "proven coworking Bangalore",
    "successful coworking Bangalore",
    "growing coworking Bangalore",
    "expanding coworking Bangalore",
    "popular coworking Bangalore",
    "trending coworking Bangalore",
    "in demand coworking Bangalore",
    "sought after coworking Bangalore",
    "preferred coworking Bangalore",
    "Namma Bengaluru coworking",
    "Namma Basavanagudi workspace",
    "heritage Basavanagudi office",
    "cultural Basavanagudi workspace",
    "traditional South Bangalore office",
    "modern Basavanagudi coworking",
    "vibrant Basavanagudi workspace",
    "energetic coworking Bangalore",
    "dynamic workspace Basavanagudi",
    "lively coworking space",
    "passionate workspace community",
    "ambitious entrepreneur space",
    "dream workspace Bangalore",
    "aspiration workspace Basavanagudi",
    "vision workspace Bangalore",
    "mission workspace Basavanagudi",
    "purpose workspace Bangalore",
    "meaningful workspace Basavanagudi",
    "fulfilling workspace Bangalore",
    "satisfying workspace Basavanagudi",
    "rewarding workspace Bangalore",
    "gratifying workspace Basavanagudi",
    "enriching workspace Bangalore",
    "empowering workspace Basavanagudi",
    "enabling workspace Bangalore",
    "facilitating workspace Basavanagudi",
    "supporting workspace Bangalore",
    "nurturing workspace Basavanagudi",
    "cultivating workspace Bangalore",
    "fostering workspace Basavanagudi",
    "developing workspace Bangalore",
    "enhancing workspace Basavanagudi",
    "improving workspace Bangalore",
    "elevating workspace Basavanagudi",
    "uplifting workspace Bangalore",
    "inspiring workspace Basavanagudi",
    "motivating workspace Bangalore",
    "encouraging workspace Basavanagudi",
    "stimulating workspace Bangalore",
    "exciting workspace Basavanagudi",
    "thrilling workspace Bangalore",
    "exhilarating workspace Basavanagudi",
    "energizing workspace Bangalore",
    "invigorating workspace Basavanagudi",
    "refreshing workspace Bangalore",
    "revitalizing workspace Basavanagudi",
    "rejuvenating workspace Bangalore",
    "renewing workspace Basavanagudi",
    "restoring workspace Bangalore",
    "healing workspace Basavanagudi",
    "therapeutic workspace Bangalore",
    "meditative workspace Basavanagudi",
    "contemplative workspace Bangalore",
    "reflective workspace Basavanagudi",
    "thoughtful workspace Bangalore",
    "mindful workspace Basavanagudi",
    "conscious workspace Bangalore",
    "aware workspace Basavanagudi",
    "present workspace Bangalore",
    "focused workspace Basavanagudi",
    "concentrated workspace Bangalore",
    "attentive workspace Basavanagudi",
    "dedicated workspace Bangalore",
    "committed workspace Basavanagudi",
    "devoted workspace Bangalore",
    "loyal workspace Basavanagudi",
    "faithful workspace Bangalore",
    "steadfast workspace Basavanagudi",
    "resolute workspace Bangalore",
    "determined workspace Basavanagudi",
    "persistent workspace Bangalore",
    "persevering workspace Basavanagudi",
    "enduring workspace Bangalore",
    "lasting workspace Basavanagudi",
    "enduring workspace Bangalore",
    "sustainable workspace Basavanagudi",
    "eco-friendly workspace Bangalore",
    "green workspace Basavanagudi",
    "environmentally conscious workspace",
    "responsible workspace Bangalore",
    "ethical workspace Basavanagudi",
    "principled workspace Bangalore",
    "moral workspace Basavanagudi",
    "virtuous workspace Bangalore",
    "righteous workspace Basavanagudi",
    "noble workspace Bangalore",
    "honorable workspace Basavanagudi",
    "dignified workspace Bangalore",
    "respectable workspace Basavanagudi",
    "esteemed workspace Bangalore",
    "prestigious workspace Basavanagudi",
    "distinguished workspace Bangalore",
    "renowned workspace Basavanagudi",
    "famous workspace Bangalore",
    "well-known workspace Basavanagudi",
    "celebrated workspace Bangalore",
    "acclaimed workspace Basavanagudi",
    "praised workspace Bangalore",
    "commended workspace Basavanagudi",
    "applauded workspace Bangalore",
    "cheered workspace Basavanagudi",
    "encouraged workspace Bangalore",
    "supported workspace Basavanagudi",
    "backed workspace Bangalore",
    "sponsored workspace Basavanagudi",
    "funded workspace Bangalore",
    "financed workspace Basavanagudi",
    "invested workspace Bangalore",
    "capitalized workspace Basavanagudi",
    "monetized workspace Bangalore",
    "commercialized workspace Basavanagudi",
    "marketed workspace Bangalore",
    "promoted workspace Basavanagudi",
    "advertised workspace Bangalore",
    "publicized workspace Basavanagudi",
    "announced workspace Bangalore",
    "declared workspace Basavanagudi",
    "proclaimed workspace Bangalore",
    "pronounced workspace Basavanagudi",
    "stated workspace Bangalore",
    "asserted workspace Basavanagudi",
    "affirmed workspace Bangalore",
    "confirmed workspace Basavanagudi",
    "validated workspace Bangalore",
    "verified workspace Basavanagudi",
    "authenticated workspace Bangalore",
    "certified workspace Basavanagudi",
    "accredited workspace Bangalore",
    "licensed workspace Basavanagudi",
    "authorized workspace Bangalore",
    "approved workspace Basavanagudi",
    "sanctioned workspace Bangalore",
    "endorsed workspace Basavanagudi",
    "ratified workspace Bangalore",
  ],
  openGraph: {
    title: "Spacio Workspace – Premium Coworking Space in Bangalore | Basavanagudi & Jayanagar",
    description:
      "Bangalore's premier coworking space for Gen Z entrepreneurs and startups. Private cabins, dedicated desks, meeting rooms, virtual offices. Lightning-fast internet, 24/7 access, premium amenities. Book your free tour!",
    url: "https://spacioworkspace.com/",
    siteName: "Spacio Workspace",
    locale: "en_IN",
    type: "website",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Spacio Workspace - Premium Coworking Space in Bangalore",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Spacio Workspace – Premium Coworking Space in Bangalore",
    description: "Bangalore's #1 coworking space for Gen Z entrepreneurs. Private cabins, dedicated desks, meeting rooms. Book your free tour!",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "https://spacioworkspace.com/",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    "@id": "https://spacioworkspace.com/#organization",
    name: "Spacio Workspace",
    description: "Premium coworking space in Bangalore offering private cabins, dedicated desks, meeting rooms, and virtual offices for entrepreneurs, startups, and freelancers.",
    url: "https://spacioworkspace.com",
    logo: "https://spacioworkspace.com/logo.png",
    image: "https://spacioworkspace.com/og-image.jpg",
    telephone: "+917022780310",
    email: "hello@spacioworkspace.com",
    address: {
      "@type": "PostalAddress",
      streetAddress: "No 7, Sree Devi Complex, NAT Street",
      addressLocality: "Basavanagudi",
      addressRegion: "Karnataka",
      postalCode: "560004",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9449135",
      longitude: "77.5658325",
    },
    openingHoursSpecification: [
      {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        opens: "00:00",
        closes: "23:59",
      },
    ],
    priceRange: "₹₹",
    servesCuisine: "Indian",
    areaServed: {
      "@type": "City",
      name: "Bangalore",
    },
    sameAs: [
      "https://www.google.com/maps/place/Spacio+Workspace",
    ],
    aggregateRating: {
      "@type": "AggregateRating",
      ratingValue: "4.8",
      reviewCount: "50",
    },
  };

  const breadcrumbStructuredData = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Home",
        item: "https://spacioworkspace.com",
      },
    ],
  };

  return (
    <html lang="en-IN">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=AW-10930874990"
          strategy="afterInteractive"
        />
        <Script id="google-ads-tag" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'AW-10930874990');
          `}
        </Script>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbStructuredData) }}
        />
        <Header />
        <main>{children}</main>
        <Footer />
        <FloatingWhatsApp />
        <ScrollBasedLeadCapture />
      </body>
    </html>
  );
}
